# Generated by Django 5.0 on 2025-05-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rem_type', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('call', 'Call')], default='sms', max_length=10)),
                ('message', models.TextField()),
                ('rem_date', models.DateTimeField()),
            ],
        ),
    ]
